/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.IkonAyarlari;
import gui.ayarlar.Mesaj;
import gui.ayarlar.TextAyarlari;
import gui.veritabani.IBilgiKontrol;
import gui.veritabani.transactions.HesapBilgileri;
import javax.swing.JOptionPane;

/**
 *
 * @author Hakan
 */
public  class KullaniciBilgiGuncelle extends javax.swing.JFrame implements IDuzenleyici,IBilgiKontrol {

    /**
     * Creates new form KullaniciBilgiGuncelle
     */
    private String eskiTelNo=null;
    public KullaniciBilgiGuncelle() {
        initComponents();
        getEdits();
    }

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        kullaniciBilgiGuncellePanel.setFocusable(true);
        TextAyarlari.setOnlyNumber(telNoText);
        TextAyarlari.setMaxLimit(telNoText, 11);
        this.telNoText.setText(getHesapBilgileri().getTelNo());
        this.eskiTelNo=telNoText.getText();
        this.kullaniciAdSoyadLabel.setText("Sayın "+getHesapBilgileri().getAdSoyad());
    }
  @Override
    public boolean bilgilerGecerliMi() {
        return !(this.telNoText.getText().equals(""));
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
        return HesapBilgileri.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullaniciBilgiGuncellePanel = new javax.swing.JPanel();
        sayinLabel = new javax.swing.JLabel();
        kullaniciAdSoyadLabel = new javax.swing.JLabel();
        cikisIkon = new javax.swing.JLabel();
        telNoLabel = new javax.swing.JLabel();
        telNoText = new javax.swing.JTextField();
        telNoGuncelleIcon = new javax.swing.JLabel();
        sifreLabel = new javax.swing.JLabel();
        sifreText = new javax.swing.JTextField();
        sifreGuncelleIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KULLANICI BİLGİLERİ GÜNCELLEME");

        sayinLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sayinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sayinLabel.setText("SAYIN");

        kullaniciAdSoyadLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kullaniciAdSoyadLabel.setText("[KULLANICI ADI SOYADI]");

        cikisIkon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/İconlar/logoCikis.png"))); // NOI18N
        cikisIkon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikisIkonMouseClicked(evt);
            }
        });

        telNoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telNoLabel.setText("Telefon Numaranız:");

        telNoText.setEnabled(false);
        telNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNoTextActionPerformed(evt);
            }
        });

        telNoGuncelleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/İconlar/logoGuncelle.png"))); // NOI18N
        telNoGuncelleIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telNoGuncelleIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telNoGuncelleIconMouseClicked(evt);
            }
        });

        sifreLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sifreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sifreLabel.setText("Şifreniz:");

        sifreText.setText("**************");
        sifreText.setEnabled(false);
        sifreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreTextActionPerformed(evt);
            }
        });

        sifreGuncelleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/İconlar/logoGuncelle.png"))); // NOI18N
        sifreGuncelleIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sifreGuncelleIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifreGuncelleIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kullaniciBilgiGuncellePanelLayout = new javax.swing.GroupLayout(kullaniciBilgiGuncellePanel);
        kullaniciBilgiGuncellePanel.setLayout(kullaniciBilgiGuncellePanelLayout);
        kullaniciBilgiGuncellePanelLayout.setHorizontalGroup(
            kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciBilgiGuncellePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cikisIkon)
                .addGap(91, 91, 91)
                .addGroup(kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullaniciAdSoyadLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sayinLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciBilgiGuncellePanelLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullaniciBilgiGuncellePanelLayout.createSequentialGroup()
                        .addComponent(sifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(sifreGuncelleIcon))
                    .addGroup(kullaniciBilgiGuncellePanelLayout.createSequentialGroup()
                        .addComponent(telNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(telNoGuncelleIcon)))
                .addGap(51, 51, 51))
        );
        kullaniciBilgiGuncellePanelLayout.setVerticalGroup(
            kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciBilgiGuncellePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cikisIkon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kullaniciBilgiGuncellePanelLayout.createSequentialGroup()
                        .addComponent(sayinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kullaniciAdSoyadLabel)))
                .addGap(55, 55, 55)
                .addGroup(kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telNoGuncelleIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifreGuncelleIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kullaniciBilgiGuncellePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        kullaniciBilgiGuncellePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {telNoGuncelleIcon, telNoLabel, telNoText});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kullaniciBilgiGuncellePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kullaniciBilgiGuncellePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cikisIkonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisIkonMouseClicked
        ActionAyarlari.SetVisible(this, new KullaniciEkrani());
    }//GEN-LAST:event_cikisIkonMouseClicked

    private void telNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNoTextActionPerformed
       
    }//GEN-LAST:event_telNoTextActionPerformed

    private void sifreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreTextActionPerformed
       
    }//GEN-LAST:event_sifreTextActionPerformed
    private int tiklamaSayaci=0;
    private void telNoGuncelleIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telNoGuncelleIconMouseClicked
        if (tiklamaSayaci==0) { //Daha önce tıklanmamış
        telNoText.setEnabled(true);
       IkonAyarlari.ikonDegistir(telNoGuncelleIcon,"logoGuncelle2");
        tiklamaSayaci++;
        }
        else{//Daha önce tıklanmışsa
            telNoText.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Telefon Numarası Güncellendi.");
            IkonAyarlari.setOriginalIkon(telNoGuncelleIcon);
            tiklamaSayaci=0;
        }
    }//GEN-LAST:event_telNoGuncelleIconMouseClicked

    private void telNoYenile(){
        if (this.bilgilerGecerliMi()) {
            String yeniTelNo=this.telNoText.getText().trim();
        }else{
            Mesaj.bosOlamazMesaji(this);
        }
    }
    private void sifreGuncelleIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreGuncelleIconMouseClicked
       ActionAyarlari.SetVisible(this, new SifreGuncellemeEkrani());
    }//GEN-LAST:event_sifreGuncelleIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciBilgiGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cikisIkon;
    private javax.swing.JLabel kullaniciAdSoyadLabel;
    private javax.swing.JPanel kullaniciBilgiGuncellePanel;
    private javax.swing.JLabel sayinLabel;
    private javax.swing.JLabel sifreGuncelleIcon;
    private javax.swing.JLabel sifreLabel;
    private javax.swing.JTextField sifreText;
    private javax.swing.JLabel telNoGuncelleIcon;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoText;
    // End of variables declaration//GEN-END:variables

    

   
   
}
