/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.ButonAyarları;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.TextAyarlari;
import java.awt.Color;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author Hakan
 */
public class SifreGuncellemeEkrani extends javax.swing.JFrame implements IDuzenleyici {

    /**
     * Creates new form SifreGuncellemeEkrani
     */
    public SifreGuncellemeEkrani() {
        initComponents();
        getEdits();
    }

    @Override
    public void getEdits() {
       this.setLocationRelativeTo(null);
       sifreGuncellemePanel.setFocusable(true);
       TextAyarlari.setOnlyNumber(telNoText);
       TextAyarlari.setMaxLimit(telNoText, 11);
       TextAyarlari.setOnlyNumber(tcNoText);
       TextAyarlari.setMaxLimit(tcNoText, 11);
       
       
    }

    public JTextField getEskiSifreText() {
        return eskiSifreText;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean eskiSifreTextAktifmi(){
        return this.getEskiSifreText().isEnabled();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sifreGuncellemePanel = new javax.swing.JPanel();
        cikisIkon = new javax.swing.JLabel();
        sifreYenilemeLabel = new javax.swing.JLabel();
        tbNoLabel = new javax.swing.JLabel();
        tcNoText = new javax.swing.JTextField();
        telNoLabel = new javax.swing.JLabel();
        telNoText = new javax.swing.JTextField();
        guvenlikSoruLabel = new javax.swing.JLabel();
        guvenlikSoruText = new javax.swing.JTextField();
        eskiSifreLabel = new javax.swing.JLabel();
        eskiSifreText = new javax.swing.JTextField();
        yeniSifreText = new javax.swing.JTextField();
        yeniSifreLabel = new javax.swing.JLabel();
        yeniSifreTekrarLabel = new javax.swing.JLabel();
        yeniSifreTekrarText = new javax.swing.JTextField();
        sifreYenileButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sifreGuncellemePanel.setBackground(new java.awt.Color(204, 255, 204));

        cikisIkon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/İconlar/logoCikis.png"))); // NOI18N
        cikisIkon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikisIkonMouseClicked(evt);
            }
        });

        sifreYenilemeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sifreYenilemeLabel.setText("Şifre Yenileme");

        tbNoLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tbNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tbNoLabel.setText("T.C. No:");

        telNoLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        telNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telNoLabel.setText("Telefon No:");

        guvenlikSoruLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        guvenlikSoruLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guvenlikSoruLabel.setText("Güvenlik Sorusu Cevap:");

        eskiSifreLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        eskiSifreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eskiSifreLabel.setText("Eski Şifre:");

        yeniSifreLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        yeniSifreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yeniSifreLabel.setText("Yeni Şifre:");

        yeniSifreTekrarLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        yeniSifreTekrarLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yeniSifreTekrarLabel.setText("Yeni Şifre Tekrar:");

        sifreYenileButon.setText("Şifreyi Yenile");
        sifreYenileButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sifreYenileButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sifreYenileButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sifreYenileButonMouseExited(evt);
            }
        });
        sifreYenileButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreYenileButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sifreGuncellemePanelLayout = new javax.swing.GroupLayout(sifreGuncellemePanel);
        sifreGuncellemePanel.setLayout(sifreGuncellemePanelLayout);
        sifreGuncellemePanelLayout.setHorizontalGroup(
            sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreGuncellemePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sifreGuncellemePanelLayout.createSequentialGroup()
                        .addComponent(cikisIkon)
                        .addGap(134, 134, 134)
                        .addComponent(sifreYenilemeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifreGuncellemePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yeniSifreLabel)
                            .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(guvenlikSoruLabel)
                                .addComponent(tbNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eskiSifreLabel))
                            .addComponent(yeniSifreTekrarLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(guvenlikSoruText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eskiSifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yeniSifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(yeniSifreTekrarText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(sifreGuncellemePanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(sifreYenileButon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sifreGuncellemePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guvenlikSoruText, tcNoText, telNoText});

        sifreGuncellemePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {eskiSifreLabel, guvenlikSoruLabel, tbNoLabel, telNoLabel, yeniSifreLabel, yeniSifreTekrarLabel});

        sifreGuncellemePanelLayout.setVerticalGroup(
            sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreGuncellemePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sifreYenilemeLabel)
                    .addComponent(cikisIkon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNoLabel)
                    .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNoLabel)
                    .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guvenlikSoruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guvenlikSoruText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eskiSifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eskiSifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeniSifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeniSifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sifreGuncellemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yeniSifreTekrarText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeniSifreTekrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sifreYenileButon)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        sifreGuncellemePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {guvenlikSoruText, tcNoText, telNoText});

        sifreGuncellemePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {eskiSifreLabel, guvenlikSoruLabel, tbNoLabel, telNoLabel, yeniSifreLabel, yeniSifreTekrarLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sifreGuncellemePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sifreGuncellemePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cikisIkonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisIkonMouseClicked
        if (eskiSifreTextAktifmi()) {
            ActionAyarlari.SetVisible(this, new KullaniciEkrani());
        }else{
        ActionAyarlari.SetVisible(this, new GirisEkrani());
        }
        
    }//GEN-LAST:event_cikisIkonMouseClicked

    private void sifreYenileButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreYenileButonMouseEntered
        ButonAyarları.setBgFg(sifreYenileButon, Color.BLACK, Color.WHITE);
    }//GEN-LAST:event_sifreYenileButonMouseEntered

    private void sifreYenileButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreYenileButonMouseExited
        ButonAyarları.setOriginalBgFg(sifreYenileButon);
    }//GEN-LAST:event_sifreYenileButonMouseExited

    private void sifreYenileButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreYenileButonActionPerformed
        JOptionPane.showMessageDialog(this, "Şifre Başarıyla Güncellendi.");
        if (eskiSifreTextAktifmi()) {
            ActionAyarlari.SetVisible(this, new KullaniciEkrani());
        }else{
        ActionAyarlari.SetVisible(this, new GirisEkrani());
        }
        
    }//GEN-LAST:event_sifreYenileButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SifreGuncellemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SifreGuncellemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SifreGuncellemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SifreGuncellemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SifreGuncellemeEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cikisIkon;
    private javax.swing.JLabel eskiSifreLabel;
    private javax.swing.JTextField eskiSifreText;
    private javax.swing.JLabel guvenlikSoruLabel;
    private javax.swing.JTextField guvenlikSoruText;
    private javax.swing.JPanel sifreGuncellemePanel;
    private javax.swing.JButton sifreYenileButon;
    private javax.swing.JLabel sifreYenilemeLabel;
    private javax.swing.JLabel tbNoLabel;
    private javax.swing.JTextField tcNoText;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoText;
    private javax.swing.JLabel yeniSifreLabel;
    private javax.swing.JLabel yeniSifreTekrarLabel;
    private javax.swing.JTextField yeniSifreTekrarText;
    private javax.swing.JTextField yeniSifreText;
    // End of variables declaration//GEN-END:variables

    
}
